import { AuthProvider } from '@/context/Authcontext';
import Navbar from '../components/Navbar';
import './globals.css';

export const metadata = {
  title: 'My App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body>
          <Navbar />
          <div className="container mx-auto">
            {children}
          </div>
        </body>
      </html>
    </AuthProvider>
  );
}
